# Generated by Django 3.0 on 2019-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
