# Generated by Django 3.0 on 2019-12-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191205_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
