# Generated by Django 3.0 on 2019-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191205_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='store/photos/producers', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='store/photos/products', verbose_name='Photo'),
        ),
    ]
